steps:
  # Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/election-repo/election-assistant:$COMMIT_SHA', '.']
  
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/election-repo/election-assistant:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'election-assistant'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/election-repo/election-assistant:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--set-secrets'
      - 'Maps_API_KEY=Maps_API_KEY:latest,CIVIC_INFO_API_KEY=CIVIC_INFO_API_KEY:latest'

options:
  logging: CLOUD_LOGGING_ONLY
